let nombres = ['Pepe', 'Fulano', 'Sutano', 'Perensejo']
console.log(nombres[2])
    /**
     * POP(): ELIMINAR EL ULTIMO ELEMENTO
     * SHIFT(): ELIMINAR EL PRIMER ELEMENTO DEL ARRAY
     * PUSH(): AGREGAR ELEMENTOS AL FINAL DEL ARREGLO
     * UNSHIFT(): AGREGAR ELEMENTOS AL INICIO DEL ARREGLO
     * SPLICE(): PERMITE AGREGAR ) ELIMINAR ELEMENTOS EN UNA POSICION EN ESPECIFICO
     * CONCAT(): PERMITE UNIR ARRAYS
     * SORT(): ORDERNAR EL ARREGLO
     * REVERSE(): INVERTIR EL ORDEN DEL ARRAY
     * INDEXOF(): BUSCAR LA POSICION DE UN ELEMENTO
     */

console.log(nombres.pop())